// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtOHcxUrHtOuppMsa_xvyxQWshituW7b0',
    appId: '1:235935560901:web:4e2d1b184612bf96b3acac',
    messagingSenderId: '235935560901',
    projectId: 'ubon-8822',
    authDomain: 'ubon-8822.firebaseapp.com',
    storageBucket: 'ubon-8822.appspot.com',
    measurementId: 'G-51754JQK0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMXs8KtY6u0UCxjisFWQO6OMde3jRf6kw',
    appId: '1:235935560901:android:4720a70deb25e7fcb3acac',
    messagingSenderId: '235935560901',
    projectId: 'ubon-8822',
    storageBucket: 'ubon-8822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqQGWtzfQDLy3PCtSn86zASZYPXTqi1jA',
    appId: '1:235935560901:ios:9c5db4eec7166dceb3acac',
    messagingSenderId: '235935560901',
    projectId: 'ubon-8822',
    storageBucket: 'ubon-8822.appspot.com',
    iosBundleId: 'com.example.ubonApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqQGWtzfQDLy3PCtSn86zASZYPXTqi1jA',
    appId: '1:235935560901:ios:9c5db4eec7166dceb3acac',
    messagingSenderId: '235935560901',
    projectId: 'ubon-8822',
    storageBucket: 'ubon-8822.appspot.com',
    iosBundleId: 'com.example.ubonApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtOHcxUrHtOuppMsa_xvyxQWshituW7b0',
    appId: '1:235935560901:web:8c9acaaf302c9ad9b3acac',
    messagingSenderId: '235935560901',
    projectId: 'ubon-8822',
    authDomain: 'ubon-8822.firebaseapp.com',
    storageBucket: 'ubon-8822.appspot.com',
    measurementId: 'G-8D3G4KP3Y4',
  );

}