// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJkrvYCnbnvMcZNrA4oioMBbNHs91gAU',
    appId: '1:596535302134:web:ec114c55b29c7610d819d7',
    messagingSenderId: '596535302134',
    projectId: 'meet-396d5',
    authDomain: 'meet-396d5.firebaseapp.com',
    storageBucket: 'meet-396d5.appspot.com',
    measurementId: 'G-74PMDD7C9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhJjaun8BF9H-F1xVlaZ5Vi4-7x_e_l2o',
    appId: '1:596535302134:android:128efb8b6b758a13d819d7',
    messagingSenderId: '596535302134',
    projectId: 'meet-396d5',
    storageBucket: 'meet-396d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC66j4uwm7N-269jvs1Ao84ta3X8_58Sis',
    appId: '1:596535302134:ios:0d3096889ddbabf5d819d7',
    messagingSenderId: '596535302134',
    projectId: 'meet-396d5',
    storageBucket: 'meet-396d5.appspot.com',
    androidClientId: '596535302134-vkgjnjqsvge37kcs6ecdungjil1vc5vj.apps.googleusercontent.com',
    iosClientId: '596535302134-lsek24ir921uf29li61h4opb5qrlsg7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.ubonApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC66j4uwm7N-269jvs1Ao84ta3X8_58Sis',
    appId: '1:596535302134:ios:0d3096889ddbabf5d819d7',
    messagingSenderId: '596535302134',
    projectId: 'meet-396d5',
    storageBucket: 'meet-396d5.appspot.com',
    androidClientId: '596535302134-vkgjnjqsvge37kcs6ecdungjil1vc5vj.apps.googleusercontent.com',
    iosClientId: '596535302134-lsek24ir921uf29li61h4opb5qrlsg7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.ubonApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmJkrvYCnbnvMcZNrA4oioMBbNHs91gAU',
    appId: '1:596535302134:web:7022750c1a24f8fbd819d7',
    messagingSenderId: '596535302134',
    projectId: 'meet-396d5',
    authDomain: 'meet-396d5.firebaseapp.com',
    storageBucket: 'meet-396d5.appspot.com',
    measurementId: 'G-4TE5GSYJCW',
  );

}